from .existing_requests import existing_requests_bp
from .new_request import new_request_bp
from .recommendation import recommendation_bp
from .shift_request import shift_request_bp
from .vehicle_request import vehicle_request_bp
from .volunteer import volunteer_bp
from .volunteer_all import volunteer_all_bp
from .volunteer_availability import volunteer_availability_bp
from .volunteer_preferred_hours import volunteer_preferred_hours_bp
from .volunteer_shifts import volunteer_shifts_bp
from .volunteer_status import volunteer_status_bp
from .authentication import authentication_bp
from .reference_data import reference_bp
from .user_role import user_role_bp
from .asset_type_role import asset_type_role_bp
from .user_type import user_type_bp
from .tenancy_config import tenancy_config_bp
from .tutorial_quiz import tutorial_quiz_bp
from .email import email_bp
from .volunteer_unavailability import volunteer_unavailability_bp
from .user import user_bp
from .chatbot import chatbot_bp
from .profile import profile_bp
