"""reference_data

Revision ID: 0229402be7c0
Revises: 676d13fb7131
Create Date: 2021-04-04 08:31:31.420564

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = '0229402be7c0'
down_revision = '676d13fb7131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('qualifications')
    # ### end Alembic commands ###
