"""user_role_fix

Revision ID: 33d8eed52ed2
Revises: dce58a9d1e56
Create Date: 2021-04-10 16:27:34.214771

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = '33d8eed52ed2'
down_revision = 'dce58a9d1e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_type_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type_id', sa.Integer(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_type.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_type_role')
    # ### end Alembic commands ###
