"""init

Revision ID: 676d13fb7131
Revises: 
Create Date: 2021-03-20 12:28:59.387593

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = '676d13fb7131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_type', sa.Enum('VOLUNTEER', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('incorrect_password_count', sa.Integer(), nullable=True),
    sa.Column('last_sign_in_datetime', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('mobile_number', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('preferred_hours', sa.Integer(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('possible_roles', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('availabilities', sa.JSON(), nullable=True),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_table('asset_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_request_vehicle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('from', sa.DateTime(), nullable=True),
    sa.Column('to', sa.DateTime(), nullable=True),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['asset_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_request_volunteer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['asset_request_vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_request_volunteer')
    op.drop_table('asset_request_vehicle')
    op.drop_table('asset_request')
    op.drop_table('user')
    # ### end Alembic commands ###
