"""Added backend logo storage

Revision ID: 7bb432468c73
Revises: 386e381397c1
Create Date: 2021-10-15 08:27:02.378410

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bb432468c73'
down_revision = '386e381397c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenancy_config', sa.Column('logo_mimetype', sa.Text(), nullable=False))
    op.add_column('tenancy_config', sa.Column('logo_name', sa.Text(), nullable=False))
    op.alter_column('tenancy_config', 'logo', existing_type=mysql.VARCHAR(length=256), nullable=False, type_=mysql.TEXT)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenancy_config', 'logo',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_column('tenancy_config', 'logo_name')
    op.drop_column('tenancy_config', 'logo_mimetype')
    # ### end Alembic commands ###
