"""Tenancy Configurations

Revision ID: 386e381397c1
Revises: a82e602101f6
Create Date: 2021-09-19 10:19:38.126391

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '386e381397c1'
down_revision = 'a82e602101f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenancy_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('font', sa.String(length=256), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.Column('navbar_colour', sa.String(length=256), nullable=False),
    sa.Column('background_colour', sa.String(length=256), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('last_update_datetime', sa.DateTime(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenancy_config')
    # ### end Alembic commands ###
