"""Changed logo store to binary

Revision ID: 5500788ed080
Revises: 7bb432468c73
Create Date: 2021-10-18 10:47:11.886137

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5500788ed080'
down_revision = '7bb432468c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenancy_config', 'logo', existing_type=mysql.VARCHAR(length=256), nullable=False, type_=mysql.BLOB)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenancy_config', 'logo',
                    existing_type=mysql.TEXT,
                    nullable=True)
    # ### end Alembic commands ###
