"""add_role_code

Revision ID: 8f117f131993
Revises: 33d8eed52ed2
Create Date: 2021-04-10 16:33:49.565102

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = '8f117f131993'
down_revision = '33d8eed52ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('code', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'code')
    # ### end Alembic commands ###
