"""Initial

Revision ID: 93f8567b7eac
Revises: 
Create Date: 2021-03-14 17:36:33.977776

"""
from alembic import op
import sys

from backend.domain.guid import GUID

sys.path = ['', '..'] + sys.path[1:]
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f8567b7eac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('firstName', sa.String(length=256), nullable=False),
    sa.Column('lastName', sa.String(length=256), nullable=False),
    sa.Column('mobileNo', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('rowInsertDT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobileNo')
    )
    op.create_table('volunteer',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('firstName', sa.String(length=256), nullable=True),
    sa.Column('lastName', sa.String(length=256), nullable=True),
    sa.Column('mobileNo', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('prefHours', sa.Integer(), nullable=True),
    sa.Column('expYears', sa.Integer(), nullable=True),
    sa.Column('possibleRoles', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('availabilities', sa.JSON(), nullable=True),
    sa.Column('lastUpdateDt', sa.DateTime(), nullable=False),
    sa.Column('rowInsertDT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobileNo')
    )
    op.create_table('asset-request',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('idAdmin', GUID(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('lastUpdateDt', sa.DateTime(), nullable=False),
    sa.Column('rowInsertDT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idAdmin'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset-request_vehicle',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('idRequest', GUID(length=32), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('from', sa.DateTime(), nullable=True),
    sa.Column('to', sa.DateTime(), nullable=True),
    sa.Column('lastUpdateDt', sa.DateTime(), nullable=False),
    sa.Column('rowInsertDT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idRequest'], ['asset-request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset-request_volunteer',
    sa.Column('id', GUID(length=32), nullable=False),
    sa.Column('idVolunteer', GUID(length=32), nullable=True),
    sa.Column('idVehicle', GUID(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('lastUpdateDt', sa.DateTime(), nullable=False),
    sa.Column('rowInsertDT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idVehicle'], ['asset-request_vehicle.id'], ),
    sa.ForeignKeyConstraint(['idVolunteer'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset-request_volunteer')
    op.drop_table('asset-request_vehicle')
    op.drop_table('asset-request')
    op.drop_table('volunteer')
    op.drop_table('admin')
    # ### end Alembic commands ###
