"""Add fk's

Revision ID: 9e60c4a25e61
Revises: 8f117f131993
Create Date: 2021-05-01 16:33:09.440250

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]


# revision identifiers, used by Alembic.
revision = '9e60c4a25e61'
down_revision = '8f117f131993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_request_vehicle', sa.Column('asset_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset_request_vehicle', 'asset_type', ['asset_type_id'], ['id'])
    op.add_column('asset_request_volunteer', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset_request_volunteer', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_request_volunteer', type_='foreignkey')
    op.drop_column('asset_request_volunteer', 'role_id')
    op.drop_constraint(None, 'asset_request_vehicle', type_='foreignkey')
    op.drop_column('asset_request_vehicle', 'asset_type_id')
    # ### end Alembic commands ###
