"""new UserType Root Admin

Revision ID: a82e602101f6
Revises: 9e60c4a25e61
Create Date: 2021-08-23 14:58:42.415543

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
sys.path = ['', '..'] + sys.path[1:]

# revision identifiers, used by Alembic.
revision = 'a82e602101f6'
down_revision = '9e60c4a25e61'
branch_labels = None
depends_on = None


# noinspection SqlResolve
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TABLE user MODIFY COLUMN user_type ENUM('VOLUNTEER','ADMIN', 'ROOT_ADMIN');")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
