"""new UserType Root Admin

Revision ID: a82e602101f6
Revises: 9e60c4a25e61
Create Date: 2021-08-23 14:58:42.415543

"""
from alembic import op
import sqlalchemy as sa
from alembic import context
import sys
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import text
sys.path = ['', '..'] + sys.path[1:]

# revision identifiers, used by Alembic.
revision = 'a82e602101f6'
down_revision = '9e60c4a25e61'
branch_labels = None
depends_on = None

name = 'user_type_enum'
tmp_name = 'tmp_' + name

old_options = ('VOLUNTEER', 'ADMIN')
new_options = sorted(old_options + ('ROOT_ADMIN',))

new_type = sa.Enum(*new_options, name=name)
old_type = sa.Enum(*old_options, name=name)

tcr = sa.sql.table('user',
                   sa.Column('role', new_type, nullable=False))

def upgrade():
    op.alter_column('user', 'user_type',
               existing_type=mysql.ENUM('VOLUNTEER', 'ADMIN'),
               nullable=False, type_=mysql.ENUM('ROOT_ADMIN', 'VOLUNTEER', 'ADMIN'), server_default='VOLUNTEER')


def downgrade():

    conn = op.get_bind()
    conn.execute(text("UPDATE user SET user_type = 'VOLUNTEER' WHERE user_type = 'ROOT_ADMIN'"))
    op.alter_column('user', 'user_type',
               existing_type=mysql.ENUM('ROOT_ADMIN', 'VOLUNTEER', 'ADMIN'),
               nullable=False, type_=mysql.ENUM('VOLUNTEER', 'ADMIN'), server_default='VOLUNTEER')


# # noinspection SqlResolve
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.get_context().autocommit_block():
#         op.execute("ALTER TABLE user MODIFY COLUMN role ENUM('VOLUNTEER','ADMIN', 'ROOT_ADMIN');")
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###
